### ISSUE TITLE
Can't Update Levels

### ISSUE THREAD

**Issue by fancythedeveloper** [Wayveyx/Legacy-Level-Converter#3]
The old converter allowed you to update a level by simply reconverting the same ID (or at least a level with the same name), then you can just go and redownload the level (or press "Update" if the version number was higher) to update the level ingame.

However, with this converter, if you tried converting the same ID/file, it will simply just say "Update Failed".

Also, the old converter allowed you to upload levels as unlisted, which was pretty useful.

**Comment by Wayveyx** [comment]
I will research the given issue and uploading as unlisted will be added.

**Comment by Wayveyx** [comment]
Can you provide more information here though? I have updated levels just fine using this converter before, with Freedom16 being an example of that.

**Comment by fancythedeveloper** [comment]
It's possible this might not happen with IDs but it does happen with .gmd files.
I tried reuploading the .gmd files to 1.6 to replace the broken description, but it just says Upload failed.

**Comment by Wayveyx** [comment]
Well, Freedom16 didn't use an ID either, it reuploaded as a name. However, if your original upload was before I accidentally leaked 1.6's reupload UDID and had to change it, that would probably be the source of your issue.

**Comment by fancythedeveloper** [comment]
I didn't use 1.6 reupload's UDID though, it was uploaded to my own UDID.

**Comment by Wayveyx** [comment]
Alright, I will attempt further research.
